// +build ignore

package main

import (
	"io/ioutil"
	"os"
	"strconv"
)

func main() {
	code, err := ioutil.ReadFile("ycat.libsonnet")
	if err != nil {
		panic(err)
	}
	code = strconv.AppendQuote(nil, string(code))
	code = append([]byte(`// Code generated by ycat; DO NOT EDIT.
package ycat
const ycatStdLib = `), code...)
	code = append(code, '\n')
	ioutil.WriteFile("ycat_std.go", code, os.ModePerm)

}
